-- MySQL Script generated by MySQL Workbench
-- 04/22/17 15:55:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema listatelefonica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `listatelefonica` ;

-- -----------------------------------------------------
-- Schema listatelefonica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `listatelefonica` DEFAULT CHARACTER SET utf8 ;
USE `listatelefonica` ;

-- -----------------------------------------------------
-- Table `listatelefonica`.`listatelefonica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `listatelefonica`.`listatelefonica` ;

CREATE TABLE IF NOT EXISTS `listatelefonica`.`listatelefonica` (
  `lista_id` INT NOT NULL AUTO_INCREMENT,
  `lista_nome` VARCHAR(100) NOT NULL,
  `lista_numero` VARCHAR(45) NULL,
  PRIMARY KEY (`lista_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
