-- MySQL Script generated by MySQL Workbench
-- 04/18/17 17:00:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema listatelefonica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `listatelefonica` ;

-- -----------------------------------------------------
-- Schema listatelefonica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `listatelefonica` DEFAULT CHARACTER SET utf8 ;
USE `listatelefonica` ;

-- -----------------------------------------------------
-- Table `listatelefonica`.`nome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `listatelefonica`.`nome` ;

CREATE TABLE IF NOT EXISTS `listatelefonica`.`nome` (
  `nome_id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nome_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listatelefonica`.`numeros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `listatelefonica`.`numeros` ;

CREATE TABLE IF NOT EXISTS `listatelefonica`.`numeros` (
  `telefone_id` INT NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `nome_nome_id` INT NOT NULL,
  PRIMARY KEY (`telefone_id`, `nome_nome_id`),
  INDEX `fk_numeros_nome_idx` (`nome_nome_id` ASC),
  CONSTRAINT `fk_numeros_nome`
    FOREIGN KEY (`nome_nome_id`)
    REFERENCES `listatelefonica`.`nome` (`nome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
